# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master and develop branches.
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:        
  test:
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
        
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache packages
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ./node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install packages 
      run: yarn install
      if: steps.yarn-cache.outputs.cache-hit != 'true'
    - name: Lint smart contracts
      run: yarn lint
    - name: Unit tests
      run: yarn test:unit
      env: 
        INFURA_API_KEY: ${{ secrets. INFURA_API_KEY }}
        MNEMONIC: ${{ secrets. MNEMONIC }}
    # - name: Integration tests 
    #   run: |
    #     yarn fork:mainnet > /dev/null &
    #     while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}'; do sleep 5; done
    #     yarn test:integration --network localhost
    #     kill $(lsof -t -i:8545)
